import { Html, Head, Main, NextScript, Title } from "next/document";

export const metadata = {
    title: "Next-Sitemap",
    description: "Generated by create next app",
};

export default function Document() {
    return (
        <Html lang="en">
            <Head />
            <body className="dark">
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
